title: Ender 3 NG Log
description: A log and guide of my Ender 3 NG build
theme: just-the-docs

url: https://ender3ng.themakermedic.com

aux_links:
  The Maker Medic: https://themakermedic.com

#logo:
#favicon_ico:

color_scheme: tmm

plugins:
 - jemoji

callouts:
  note:
    color: grey-lt
  alert:
    color: yellow